server:
  port: 9003

spring:
  application:
    name: TAG-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/tagdb
    username: root
    password: Yaqoob50
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

