server:
  port: 9004

spring:
  application:
    name: REPLY-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/replydb
    username: root
    password: groot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update