server:
  port: 9006

spring:
  application:
    name: LIKE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/likedb
    username: root
    password: groot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update